# Generated by Django 4.0.5 on 2022-07-14 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Servicios',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('clave', models.CharField(max_length=10)),
                ('nombreCliente', models.CharField(max_length=50, verbose_name='Nombre del cliente')),
                ('TipServ', models.CharField(max_length=200, verbose_name='Tipo de servicio')),
                ('costo', models.IntegerField()),
                ('FechaSer', models.CharField(max_length=10, verbose_name='Fecha del servicio')),
                ('imagen', models.ImageField(null=True, upload_to='fotos', verbose_name='Imagen del servicio')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de edición')),
            ],
            options={
                'verbose_name': 'Servicio',
                'verbose_name_plural': 'Servicios',
                'ordering': ['-created'],
            },
        ),
    ]
