# Generated by Django 4.0.5 on 2022-07-14 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicios',
            name='FechaSer',
            field=models.CharField(max_length=20, verbose_name='Fecha del servicio'),
        ),
        migrations.AlterField(
            model_name='servicios',
            name='clave',
            field=models.CharField(max_length=20),
        ),
    ]
